language: node_js
node_js:
  - "4"
  - "5"
  - "6"
  - "7"
  - "8"
  - "node"
script:
  - "npm run test-travis"
after_script:
  - "npm install coveralls@3.0.x && cat coverage/lcov.info | coveralls"
matrix:
  fast_finish: true
